global:
    evaluation_interval: 15s
    scrape_interval: 15s
alerting:
    alertmanagers:
        - static_configs:
            - targets:
                - alertmanager:9093
scrape_configs:
    - job_name: prometheus
      static_configs:
        - targets:
            - localhost:9090
remote_read:
    - name: test
      url: http://192.168.57.80:9090/api/v1/read
      basic_auth:
        username: ""
        password: ""
      read_recent: true
