// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// OperateLog is the predicate function for operatelog builders.
type OperateLog func(*sql.Selector)

// Permission is the predicate function for permission builders.
type Permission func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
